### ISSUE TITLE
how to get the pickle file "fine_to_coarse_dick.pickle"

### ISSUE THREAD

**Issue by HRanWang** [janghyuncho/PiCIE#6]
Traceback (most recent call last):
  File "train_picie.py", line 358, in <module>
    main(args, logger)
  File "train_picie.py", line 190, in main
    testset    = EvalCOCO(args.data_root, res=args.res, split='val', mode='test', stuff=args.stuff, thing=args.thing)
  File "/home/jinglai.whr/code/PiCIE/data/coco_eval_dataset.py", line 40, in __init__
    self.fine_to_coarse = self._get_fine_to_coarse()
  File "/home/jinglai.whr/code/PiCIE/data/coco_eval_dataset.py", line 100, in _get_fine_to_coarse
    with open(os.path.join(self.root, FINE_TO_COARSE_PATH), "rb") as dict_f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/fine_to_coarse_dict.pickle'

Hi, how to get the pickle file "fine_to_coarse_dick.pickle", thanks!

**Comment by janghyuncho** [comment]
Hi HRanWang,

My apologies, the file was in the repo in the beginning but I somehow removed accidentally. I just added the file. You can simply move the file to your 'datasets/coco/'.

Thank you! 
Jang Hyun

**Comment by HRanWang** [comment]
hi, thanks! Now I have another error here, could there be a problem with the file you just uploaded ：）
  
  ====== METRIC TEST : cosine ======
  
  Traceback (most recent call last):
    File "train_picie.py", line 358, in <module>
      main(args, logger)
    File "train_picie.py", line 200, in main
      _, _ = evaluate(args, logger, testloader, classifier1, model)
    File "/home/jinglai.whr/code/PiCIE/commons.py", line 191, in evaluate
      for i, (_, image, label) in enumerate(dataloader):
    File "/home/jinglai.whr/anaconda3/envs/picie/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
      return self._process_data(data)
    File "/home/jinglai.whr/anaconda3/envs/picie/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
      data.reraise()
    File "/home/jinglai.whr/anaconda3/envs/picie/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
      raise self.exc_type(msg)
  KeyError: Caught KeyError in DataLoader worker process 0.
  Original Traceback (most recent call last):
    File "/home/jinglai.whr/anaconda3/envs/picie/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
      data = fetcher.fetch(index)
    File "/home/jinglai.whr/anaconda3/envs/picie/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
      data = [self.dataset[idx] for idx in possibly_batched_index]
    File "/home/jinglai.whr/anaconda3/envs/picie/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
      data = [self.dataset[idx] for idx in possibly_batched_index]
    File "/home/jinglai.whr/code/PiCIE/data/coco_eval_dataset.py", line 57, in __getitem__
      return (index,) + self.transform_data(img, lbl, index)
    File "/home/jinglai.whr/code/PiCIE/data/coco_eval_dataset.py", line 91, in transform_data
      label = self._label_transform(label)
    File "/home/jinglai.whr/code/PiCIE/data/coco_eval_dataset.py", line 118, in _label_transform
      label = self.fine_to_coarse(label)    # Map to superclass indexing.
    File "/home/jinglai.whr/anaconda3/envs/picie/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2091, in __call__
      return self._vectorize_call(func=func, args=vargs)
    File "/home/jinglai.whr/anaconda3/envs/picie/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2167, in _vectorize_call
      outputs = ufunc(*inputs)
    File "/home/jinglai.whr/code/PiCIE/data/coco_eval_dataset.py", line 104, in <lambda>
      fine_to_coarse_map       = np.vectorize(lambda x: fine_to_coarse_dict[x]) # not in-place.
  KeyError: 185

**Comment by janghyuncho** [comment]
Hi WRanHwang, 

It is strange because COCO class is from 0 to 181 so I wonder how there could be 185 as class id ... Could you please tell me what command you are running exactly?

Thank you!
Jang Hyun

**Comment by janghyuncho** [comment]
I am unable to reproduce this with the same code so I am guessing perhaps the dataset/ annotations/ json files are different? 

I am sorry for the inconvenience. 

Thank you,
Jang Hyun

**Comment by HRanWang** [comment]
Most likely, there is a problem with my JSON file. Which annotation JSON file do you use, I will download a new one and check it tomorrow. Thanks~

**Comment by janghyuncho** [comment]
Here is the [link](http://images.cocodataset.org/annotations/annotations_trainval2017.zip) for the json file. 

Let me know if it works! 

Thank you,
Jang Hyun

**Comment by HRanWang** [comment]
Hi, there is no problem with all the files, but my annotations/train2017 folder has a problem, which has been solved now, thank you!
^^

**Comment by janghyuncho** [comment]
The path is for the pre-trained weight. Please download the weight [here](https://drive.google.com/file/d/1VI5detMlDNkwWpv7M-gk7aAHgfQVebWo/view?usp=sharing) and change "eval_path" accordingly.

**Comment by wyyfffff** [comment]
> 

hi, I think I get the same question as yours, I also meet some problem with my datasets, could you tell me how you solved this? thanks

**Comment by wyyfffff** [comment]
> Hi, there is no problem with all the files, but my annotations/train2017 folder has a problem, which has been solved now, thank you! ^^

hi, I think I get the same question as yours, I also meet some problem with my datasets, could you tell me how you solved this? thanks
